version: '3.8'

secrets:
  db_root_password.txt:
    file: ./secrets/db_root_password.txt
  db_password.txt:
    file: ./secrets/db_password.txt
  wp_admin_password.txt:
    file: ./secrets/wp_admin_password.txt
  wp_user_password.txt:
    file: ./secrets/wp_user_password.txt

networks:
    inception_network:
        driver: bridge

volumes:
    mariadb:
        driver: local
        driver_opts:
            type: none
            device: /home/mdomnik.42.fr/data/mariadb
            o: bind
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: /home/mdomnik.42.fr/data/wordpress
            o: bind

services:
    mariadb:
        container_name: mariadb
        networks:
            - inception_network
        build: ./requirements/mariadb
        image: mariadb:notlatest
        secrets:
            - db_root_password.txt
            - db_password.txt
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password.txt
            MYSQL_PASSWORD_FILE: /run/secrets/db_password.txt
        env_file: .env
        volumes:
            - mariadb:/var/lib/mysql
        restart: unless-stopped
        expose:
            - "3306"
    nginx:
        container_name: nginx
        networks:
            - inception_network
        depends_on:
            - wordpress
        build: ./requirements/nginx
        image: nginx:notlatest
        env_file: .env
        volumes:
            - wordpress:/var/www/wordpress
        restart: unless-stopped
        ports:
            - "443:443"
    wordpress:
        container_name: wordpress
        networks:
            - inception_network
        depends_on:
            - mariadb
        build: ./requirements/wordpress
        image: wordpress:notlatest
        secrets:
            - db_password.txt
            - wp_admin_password.txt
            - wp_user_password.txt
        environment:
            MYSQL_PASSWORD_FILE: /run/secrets/db_password.txt
            WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password.txt
            WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password.txt
        env_file: .env
        volumes:
            - wordpress:/var/www/wordpress
        restart: unless-stopped
        expose:
            - "9000"