secrets:
  db_root_password.txt:
    file: ./secrets/db_root_password.txt
  db_password.txt:
    file: ./secrets/db_password.txt
  wp_admin_password.txt:
    file: ./secrets/wp_admin_password.txt
  wp_user_password.txt:
    file: ./secrets/wp_user_password.txt

networks:
  inception_network:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maciej/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maciej/data/wordpress


services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:notlatest
    networks: [inception_network]
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password.txt
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password.txt
    secrets:
      - db_root_password.txt
      - db_password.txt
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$$(cat /run/secrets/db_root_password.txt) --silent || mysqladmin ping -h 127.0.0.1 --silent"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:notlatest
    networks: [inception_network]
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/wordpress
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password.txt
      MYSQL_HOST: mariadb

      SITE_TITLE: ${SITE_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}

      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password.txt
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password.txt
    secrets:
      - db_password.txt
      - wp_admin_password.txt
      - wp_user_password.txt
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: nginx:notlatest
    networks: [inception_network]
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
